//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System
{
    using System;
    using System.Collections.Generic;
    
    public partial class mini
    {
        public int itemid { get; set; }
        public string itemname { get; set; }
        public Nullable<int> amountpaid { get; set; }
        public Nullable<int> change { get; set; }
    }
}
